_wandb:
    value:
        cli_version: 0.23.1
        e:
            3apz1h50j8yccmqprq5rx5d2jcqd3vkc:
                codePath: playground.source
                codePathLocal: playground.source
                cpu_count: 6
                cpu_count_logical: 6
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "478648725504"
                        used: "396755918848"
                email: tasy.levente2005@gmail.com
                executable: C:\Users\leven\PycharmProjects\propaganda\.venv\Scripts\python.exe
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-24c0c212-9556-9ec1-f72b-f56c26f3d538
                host: DESKTOP-IT7HP0U
                memory:
                    total: "17124388864"
                os: Windows-11-10.0.26100-SP0
                program: playground.source
                python: CPython 3.12.3
                root: C:\Users\leven\PycharmProjects\propaganda
                startedAt: "2025-12-19T17:27:12.326403Z"
                writerId: 3apz1h50j8yccmqprq5rx5d2jcqd3vkc
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 5
                - 33
                - 53
            "2":
                - 5
                - 33
                - 53
            "3":
                - 2
                - 16
            "4": 3.12.3
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
approach:
    value: RandomForestClassifier
dataset:
    value: propaganda_articles_1219
